name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      <% if (pnpm) {%>- name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7<%}%>
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --frozen-lockfile' : yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Lint
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> lint
      - name: Run Tests
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> test

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      <% if (pnpm) {%>- name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7<%}%>
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --no-lockfile' : yarn ? 'yarn install --no-lockfile' : 'npm install --no-shrinkwrap' %>
      - name: Run Tests
        run: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm run' %> test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      <% if (pnpm) {%>- name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7<%}%>
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: <%= pnpm ? 'pnpm' : yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= pnpm ? 'pnpm install --frozen-lockfile' : yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: <%= testAppInfo.location %>
