name: Setup pnpm
description: Setup pnpm with cache
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.25.0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    # - name: Cache pnpm modules
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.pnpm-store
    #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pnpm-
    - name: Install Dependencies
      run: pnpm install
      shell: bash
