name: "CI"
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true

jobs:
  install_dependencies:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm

  lint_js:
    name: Lint JS
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: ESLint
        run: pnpm lint

  lint_tests:
    name: Lint Tests
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: ESLint
        run: pnpm lint
        working-directory: tests

  commits:
    name: Commit Messages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v1
      - uses: wagoid/commitlint-github-action@v4.1.9

  types_library:
    name: "Types: Library"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: tsc --build --clean && tsc --build
        continue-on-error: true

  types_tests:
    name: "Types: Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: tsc --build --clean && tsc --build
        continue-on-error: true
        working-directory: tests

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    strategy:
      matrix:
        # all tests like this are slow
        slow-test:
          - basic conversion
          - snapshots conversion

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: |
          pnpm add --global ember-cli
      - name: Tests
        working-directory: 'tests'
        run: pnpm vitest --testNamePattern "${{ matrix.slow-test }}"

  tooling:
    name: Tooling
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    timeout-minutes: 2
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: Semantic Release
        run: pnpm publish:dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [tests]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - name: Release
        run: yarn publish:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: 'semantic-release'
          GIT_AUTHOR_NAME: '@semantic-release'
          GIT_COMMITTER_NAME: '@semantic-release'


  # deployed with cloudflare pages so we can have deploy previews and such
  # docs:
  #   name: Publish Docs
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   needs: [publish]

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false
  #     - uses: volta-cli/action@v1
  #     - run: yarn install
  #     - run: |
  #         cd projects/docs
  #         yarn docs:collect

  #     - name: Deploy 🚀
  #       uses: JamesIves/github-pages-deploy-action@v4.2.2
  #       with:
  #         branch: gh-pages
  #         folder: projects/docs/dist
